"""Claude Code hook registration and handler for the keshro daemon.

Manages .claude/settings.json hook entries and provides a Unix socket server
that hook scripts connect to for forwarding tool events to the daemon.

Hook flow:
  Claude Code fires PostToolUse → hook script runs → connects to daemon socket
  → sends JSON → daemon processes (track files, detect commands, collect metrics)

The hook script is installed at .claude/keshro-hook.sh and registered in
.claude/settings.json under PostToolUse for Write, Edit, and Bash matchers.
"""

from __future__ import annotations

import asyncio
import json
import logging
from pathlib import Path

logger = logging.getLogger("keshro.daemon")

# Marker to identify keshro-managed hooks in settings.json
HOOK_MARKER = "keshro-daemon"

HOOK_SCRIPT_NAME = "keshro-hook.sh"

# Tools we want to observe
WATCHED_TOOLS = ["Bash", "Write", "Edit", "MultiEdit"]


def generate_hook_script(socket_path: Path) -> str:
    """Generate the shell script that forwards hook events to the daemon socket."""
    return f"""#!/bin/bash
# Auto-generated by keshro daemon. Do not edit.
# Forwards Claude Code hook events to the keshro daemon via Unix socket.

SOCKET="{socket_path}"

# Read JSON from stdin
INPUT=$(cat)

# If daemon socket doesn't exist, exit silently
[ ! -S "$SOCKET" ] && exit 0

# Send to daemon socket (fire-and-forget, don't block Claude Code)
echo "$INPUT" | nc -U "$SOCKET" -w 1 2>/dev/null &

exit 0
"""


def install_hooks(repo_root: Path, socket_path: Path) -> None:
    """Install keshro hooks into .claude/settings.json.

    Creates the hook script and registers it for PostToolUse on
    Write, Edit, MultiEdit, and Bash tools.
    """
    claude_dir = repo_root / ".claude"
    claude_dir.mkdir(exist_ok=True)

    # Write the hook script
    hook_script = claude_dir / HOOK_SCRIPT_NAME
    hook_script.write_text(generate_hook_script(socket_path))
    hook_script.chmod(0o755)
    logger.info(f"Wrote hook script: {hook_script}")

    # Update settings.json
    settings_file = claude_dir / "settings.json"
    settings = {}
    if settings_file.exists():
        try:
            settings = json.loads(settings_file.read_text())
        except (json.JSONDecodeError, OSError):
            pass

    hooks = settings.setdefault("hooks", {})
    post_hooks = hooks.setdefault("PostToolUse", [])

    # Remove any existing keshro hooks
    post_hooks[:] = [h for h in post_hooks if not _is_keshro_hook(h)]

    # Add hooks for each watched tool
    script_path = str(hook_script.resolve())
    for tool in WATCHED_TOOLS:
        post_hooks.append(
            {
                "matcher": tool,
                "hooks": [
                    {
                        "type": "command",
                        "command": script_path,
                    }
                ],
                "_keshro": HOOK_MARKER,  # Marker for identification
            }
        )

    settings_file.write_text(json.dumps(settings, indent=2) + "\n")
    logger.info(f"Registered hooks for {WATCHED_TOOLS} in {settings_file}")


def uninstall_hooks(repo_root: Path) -> None:
    """Remove keshro hooks from .claude/settings.json."""
    claude_dir = repo_root / ".claude"
    settings_file = claude_dir / "settings.json"

    if settings_file.exists():
        try:
            settings = json.loads(settings_file.read_text())
            hooks = settings.get("hooks", {})
            post_hooks = hooks.get("PostToolUse", [])
            hooks["PostToolUse"] = [h for h in post_hooks if not _is_keshro_hook(h)]
            settings_file.write_text(json.dumps(settings, indent=2) + "\n")
            logger.info("Removed keshro hooks from settings.json")
        except (json.JSONDecodeError, OSError) as e:
            logger.warning(f"Failed to clean up settings.json: {e}")

    # Remove hook script
    hook_script = claude_dir / HOOK_SCRIPT_NAME
    hook_script.unlink(missing_ok=True)


def _is_keshro_hook(entry: dict) -> bool:
    """Check if a hook entry was installed by keshro."""
    if entry.get("_keshro") == HOOK_MARKER:
        return True
    # Fallback: check if the command references our hook script
    for hook in entry.get("hooks", []):
        cmd = hook.get("command", "")
        if HOOK_SCRIPT_NAME in cmd:
            return True
    return False


# ---------------------------------------------------------------------------
# Hook event processing
# ---------------------------------------------------------------------------


def parse_hook_event(data: bytes) -> dict | None:
    """Parse a hook event received via the Unix socket."""
    try:
        return json.loads(data.decode())
    except (json.JSONDecodeError, UnicodeDecodeError):
        logger.debug("Received malformed hook event")
        return None


def extract_file_paths(event: dict) -> list[str]:
    """Extract file paths from a hook event.

    Write/Edit events have file_path in tool_input.
    Bash events may have file paths in the command.
    """
    tool_name = event.get("tool_name", "")
    tool_input = event.get("tool_input", {})

    if tool_name in ("Write", "Edit", "MultiEdit"):
        path = tool_input.get("file_path", "")
        if path:
            return [path]
    return []


def extract_bash_command(event: dict) -> str | None:
    """Extract the bash command from a Bash tool event."""
    if event.get("tool_name") == "Bash":
        return event.get("tool_input", {}).get("command")
    return None


def detect_keshro_command(event: dict) -> tuple[str, str] | None:
    """Detect if an agent ran a keshro CLI command via Bash.

    Returns (command, task_id) if detected, e.g. ("task_done", "task-123").
    """
    cmd = extract_bash_command(event)
    if not cmd:
        return None

    # Detect "keshro task done <task-id>"
    if "keshro task done" in cmd or "kr task done" in cmd:
        parts = cmd.strip().split()
        # Find the token after "done"
        for i, part in enumerate(parts):
            if part == "done" and i + 1 < len(parts):
                task_id = parts[i + 1].strip('"').strip("'")
                if task_id and not task_id.startswith("-"):
                    return ("task_done", task_id)

    # Detect "keshro task note <task-id>"
    if "keshro task note" in cmd or "kr task note" in cmd:
        parts = cmd.strip().split()
        for i, part in enumerate(parts):
            if part == "note" and i + 1 < len(parts):
                task_id = parts[i + 1].strip('"').strip("'")
                if task_id and not task_id.startswith("-"):
                    return ("task_note", task_id)

    return None


# ---------------------------------------------------------------------------
# Unix socket server for receiving hook events
# ---------------------------------------------------------------------------


class HookSocketServer:
    """Async Unix socket server that receives hook events from Claude Code."""

    def __init__(self, socket_path: Path, on_event):
        self._socket_path = socket_path
        self._on_event = on_event
        self._server = None

    async def start(self) -> None:
        """Start listening on the Unix socket."""
        self._socket_path.unlink(missing_ok=True)
        self._socket_path.parent.mkdir(parents=True, exist_ok=True)
        self._server = await asyncio.start_unix_server(
            self._handle_client, path=str(self._socket_path)
        )
        logger.info(f"Hook socket server listening: {self._socket_path}")

    async def stop(self) -> None:
        """Stop the server and clean up."""
        if self._server:
            self._server.close()
            await self._server.wait_closed()
        self._socket_path.unlink(missing_ok=True)

    async def _handle_client(
        self, reader: asyncio.StreamReader, writer: asyncio.StreamWriter
    ) -> None:
        """Handle a single hook script connection."""
        try:
            data = await asyncio.wait_for(reader.read(65536), timeout=5.0)
            if data:
                event = parse_hook_event(data)
                if event:
                    self._on_event(event)
        except asyncio.TimeoutError:
            logger.debug("Hook client connection timed out")
        except Exception as e:
            logger.debug(f"Hook client error: {e}")
        finally:
            writer.close()
            try:
                await writer.wait_closed()
            except Exception:
                pass
